name: Create Release

on:
  push:
    branches:
      - main

jobs:
  release-on-push:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v2
        with:
          # Disabling shallow clone is recommended for improving relevancy of reporting
          fetch-depth: 0

      - id: release
        uses: rymndhng/release-on-push-action@v0.20.0
        with:
          bump_version_scheme: patch

      - name: Check Output Parameters
        run: |
          echo "Got tag name ${{ steps.release.outputs.tag_name }}"
          echo "Got release version ${{ steps.release.outputs.version }}"
          echo "SHA ${GITHUB_SHA::6}"

      - name: Create docker image api-services-portal
        uses: docker/build-push-action@v1
        with:
          registry: docker.pkg.github.com
          username: $GITHUB_ACTOR
          password: ${{ secrets.GITHUB_TOKEN }}
          repository: bcgov/api-services-portal/api-services-portal
          path: .
          dockerfile: ./Dockerfile
          push: true
          tags: ${{ steps.release.outputs.tag_name }}
          tag_with_sha: false
          build_args: APP_VERSION=${{ steps.release.outputs.version }},APP_REVISION=${GITHUB_SHA::6}

      - name: Create docker image data-feeder
        uses: docker/build-push-action@v1
        with:
          registry: docker.pkg.github.com
          username: $GITHUB_ACTOR
          password: ${{ secrets.GITHUB_TOKEN }}
          repository: bcgov/api-services-portal/data-feeder
          path: feeds
          dockerfile: feeds/Dockerfile
          push: true
          tags: ${{ steps.release.outputs.tag_name }}
          tag_with_sha: false
          build_args: APP_VERSION=${{ steps.release.outputs.version }},APP_REVISION=${GITHUB_SHA::6}
